"""Add perceptual hash

Revision ID: 00e7352f91f6
Revises: dd1dd3a7ac41
Create Date: 2026-07-05 21:13:28.653175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e7352f91f6'
down_revision = 'dd1dd3a7ac41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_analysis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('nutrition_analysis_image_hash_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_nutrition_analysis_image_hash'), ['image_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_analysis_image_hash'))
        batch_op.create_unique_constraint(batch_op.f('nutrition_analysis_image_hash_key'), ['image_hash'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
