"""add report metadata fields

Revision ID: 0c3e18474c41
Revises: d7ccf0a500f2
Create Date: 2026-08-02 23:32:04.460323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3e18474c41'
down_revision = 'd7ccf0a500f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('laboratory', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reports', schema=None) as batch_op:
        batch_op.drop_column('referred_by')
        batch_op.drop_column('laboratory')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
