"""Added chat session and chat message tables

Revision ID: 54ab6c327118
Revises: 89ef8180a285
Create Date: 2026-07-04 12:47:50.881099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ab6c327118'
down_revision = '89ef8180a285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.drop_constraint(batch_op.f('chat_messages_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_sessions', ['session_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('user_message')
        batch_op.drop_column('ai_response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_messages_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('message')
        batch_op.drop_column('role')
        batch_op.drop_column('session_id')

    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
