"""register

Revision ID: 7e1329a81c80
Revises: 00e7352f91f6
Create Date: 2026-07-05 22:41:39.144358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1329a81c80'
down_revision = '00e7352f91f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_column('target_calories')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('target_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('activity_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_calories', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
