"""add image hash

Revision ID: 97c6f8e142fb
Revises: 54ab6c327118
Create Date: 2026-07-05 14:19:04.108864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c6f8e142fb'
down_revision = '54ab6c327118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['image_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_analysis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_hash')

    # ### end Alembic commands ###
