"""Rename HealthAnalysis columns

Revision ID: d4004136577e
Revises: 7309f66ab661
Create Date: 2026-08-01 14:29:57.867080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4004136577e'
down_revision = '7309f66ab661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('health_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('findings', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('summary')
        batch_op.drop_column('overall_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('findings')
        batch_op.drop_column('health_score')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
