"""Add goal to meal_recipe

Revision ID: d7ccf0a500f2
Revises: fc330ab348ae
Create Date: 2026-08-01 18:47:11.396581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ccf0a500f2'
down_revision = 'fc330ab348ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_recipe', schema=None) as batch_op:
        batch_op.drop_column('goal')

    # ### end Alembic commands ###
