"""Add perceptual hash

Revision ID: dd1dd3a7ac41
Revises: 97c6f8e142fb
Create Date: 2026-07-05 20:19:54.968242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1dd3a7ac41'
down_revision = '97c6f8e142fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perceptual_hash', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_nutrition_analysis_perceptual_hash'), ['perceptual_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_analysis_perceptual_hash'))
        batch_op.drop_column('perceptual_hash')

    # ### end Alembic commands ###
