"""Create diet_plan table

Revision ID: fc330ab348ae
Revises: 87c6ab572966
Create Date: 2026-08-01 18:45:13.713581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc330ab348ae'
down_revision = '87c6ab572966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('breakfast', sa.Text(), nullable=True),
    sa.Column('lunch', sa.Text(), nullable=True),
    sa.Column('snack', sa.Text(), nullable=True),
    sa.Column('dinner', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['health_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diet_plan')
    # ### end Alembic commands ###
